### PR TITLE
update Handlemsg & menu.. add some features

### PR DESCRIPTION
**Pull request by thoriqazzikra**

### CODE REVIEW

**Comment by MrPawNO** [comment]
> _No description provided._



> _No description provided._

hmm.. sticker to img udh ku buat

**Comment by Fucksociety666** [comment]
> > _No description provided._
> 
> > _No description provided._
> 
> hmm.. sticker to img udh ku pull

cool textnya bug kah ??

**Comment by Fucksociety666** [comment]
> _No description provided._

 const groupsIn = groups.filter(x => x.groupMetadata.participants.map(x => [botNumber, '62895334962050@c.us'].includes(x.id._serialized)).includes(true))
            aruga.sendText(from, `Status :\n- *${loadedMsg}* Loaded Messages\n- *${groupsIn.length}* Group Joined\n- *${groups.length - groupsIn.length}* Groups Left\n- *${groups.length}* Group Chats\n- *${chatIds.length - groups.length}* Personal Chats\n- *${chatIds.length - groups.length - groupsIn.length}* Personal Chats Active\n- *${chatIds.length}* Total Chats\n- *${chatIds.length - groupsIn.length}* Total Chats Active`)
            break

        }
yg botnumber fungsinya buat??

**Comment by thoriqazzikra** [comment]
> > > _No description provided._
> > 
> > 
> > > _No description provided._
> > 
> > 
> > hmm.. sticker to img udh ku pull
> 
> cool textnya bug

coba copy dari official reponya aruga

**Comment by thoriqazzikra** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > > _No description provided._
> > > 
> > > 
> > > hmm.. sticker to img udh ku pull
> > 
> > 
> > cool textnya bug
> 
> coba copy dari official reponya aruga

itu buat munculin nomer bot dan yg laen

**Comment by thoriqazzikra** [comment]
> > _No description provided._
> 
> const groupsIn = groups.filter(x => x.groupMetadata.participants.map(x => [botNumber, '[62895334962050@c.us](mailto:62895334962050@c.us)'].includes(x.id._serialized)).includes(true))
> aruga.sendText(from, `Status :\n- *${loadedMsg}* Loaded Messages\n- *${groupsIn.length}* Group Joined\n- *${groups.length - groupsIn.length}* Groups Left\n- *${groups.length}* Group Chats\n- *${chatIds.length - groups.length}* Personal Chats\n- *${chatIds.length - groups.length - groupsIn.length}* Personal Chats Active\n- *${chatIds.length}* Total Chats\n- *${chatIds.length - groupsIn.length}* Total Chats Active`)
> break
> 
> ```
>     }
> ```
> 
> yg botnumber fungsinya buat??

ralat, bot number buat

> > > _No description provided._
> > 
> > 
> > > _No description provided._
> > 
> > 
> > hmm.. sticker to img udh ku pull
> 
> cool textnya bug

oiya lupa buat di file index, bntr ane tambahin

**Comment by MrPawNO** [comment]
> > > _No description provided._
> > 
> > 
> > > _No description provided._
> > 
> > 
> > hmm.. sticker to img udh ku pull
> 
> cool textnya bug

Buat issue aja

**Comment by TheSploit** [comment]
Buat ap coba nambah brainly? kan udah kutambah sekalian dgn scrapperny? hdeh cukup 1 aj jgn di double in

**Comment by TheSploit** [comment]
pfftt..  penjiplak :v , skip lah jadi males ngePull klo gini carany, biar ap sih? nambah yg udh ditambah ma orang?

**Comment by thoriqazzikra** [comment]
> pfftt.. penjiplak :v , skip lah jadi males ngePull klo gini carany, biar ap sih? nambah yg udh ditambah ma orang?

jiplak?
gua copy dari forks nya aruga yg whatsapp-botto-re
hadehhh gua aja ga tau lu udh duluan ngepull

**Comment by TheSploit** [comment]
> > pfftt.. penjiplak :v , skip lah jadi males ngePull klo gini carany, biar ap sih? nambah yg udh ditambah ma orang?
> 
> jiplak?
> gua copy dari forks nya aruga yg whatsapp-botto-re
> hadehhh gua aja ga tau lu udh duluan ngepull

:'(

**Comment by thoriqazzikra** [comment]
> > > pfftt.. penjiplak :v , skip lah jadi males ngePull klo gini carany, biar ap sih? nambah yg udh ditambah ma orang?
> > 
> > 
> > jiplak?
> > gua copy dari forks nya aruga yg whatsapp-botto-re
> > hadehhh gua aja ga tau lu udh duluan ngepull
> 
> :'(

udahlah, sama" copy yaudah, disini juga niatnya mau ngebantu author
gua gatau samsek klo lu udh ngepull

**Comment by Fucksociety666** [comment]
> > > > pfftt.. penjiplak :v , skip lah jadi males ngePull klo gini carany, biar ap sih? nambah yg udh ditambah ma orang?
> > > 
> > > 
> > > jiplak?
> > > gua copy dari forks nya aruga yg whatsapp-botto-re
> > > hadehhh gua aja ga tau lu udh duluan ngepull
> > 
> > 
> > :'(
> 
> udahlah, sama" copy yaudah, disini juga niatnya mau ngebantu author
> gua gatau samsek klo lu udh ngepull

mnding bantuin gw 
                await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
             } else if (quotedMsg) {
             var qmid = quotedMsgObj.sender.id
             var pic = await aruga.getProfilePicFromServer(qmid)
             var namae = quotedMsgObj.sender.name
             var sts = await aruga.getStatus(qmid)
             var adm = isGroupAdmins
             var donate = isAdmins
             const { status } = sts
              if (pic == undefined) {
              var pfp = errorurl 
              } else {
              var pfp = pic
              } 
              await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
             }
            }
            break
Screenshot pada 2020-12-07 21-50-17

**Comment by thoriqazzikra** [comment]
> > > > > pfftt.. penjiplak :v , skip lah jadi males ngePull klo gini carany, biar ap sih? nambah yg udh ditambah ma orang?
> > > > 
> > > > 
> > > > jiplak?
> > > > gua copy dari forks nya aruga yg whatsapp-botto-re
> > > > hadehhh gua aja ga tau lu udh duluan ngepull
> > > 
> > > 
> > > :'(
> > 
> > 
> > udahlah, sama" copy yaudah, disini juga niatnya mau ngebantu author
> > gua gatau samsek klo lu udh ngepull
> 
> mnding bantuin gw
> await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
> } else if (quotedMsg) {
> var qmid = quotedMsgObj.sender.id
> var pic = await aruga.getProfilePicFromServer(qmid)
> var namae = quotedMsgObj.sender.name
> var sts = await aruga.getStatus(qmid)
> var adm = isGroupAdmins
> var donate = isAdmins
> const { status } = sts
> if (pic == undefined) {
> var pfp = errorurl
> } else {
> var pfp = pic
> }
> await aruga.sendFileFromUrl(from, pfp, 'pfp.jpg', `*User Profile* ✨️ \n\n➸ *Username: ${namae}*\n\n➸ *User Info: ${status}*\n\n➸ *Admin Group: ${adm}*\n\n`)
> }
> }
> break
> Screenshot pada 2020-12-07 21-50-17

Check pull gua yg add getme!, Tu ada gua tambahin

**Pull request closed without merging**
