### PR TITLE
Add SAY MENU

### PR DESCRIPTION
**Pull request by Tanaka9531**

### CODE REVIEW

**Comment by thoriqazzikra** [comment]
mana ngab?

**Comment by Tanaka9531** [comment]
> mana ngab?

bandicam 2020-12-14 06-50-24-915
Tuh Udh Ada

**Comment by Tanaka9531** [comment]
Coba Aja Dulu

**Comment by thoriqazzikra** [comment]
> Coba Aja Dulu

file nya aja lu delete"
coba code nya sini

**Comment by Tanaka9531** [comment]
> > Coba Aja Dulu
> 
> file nya aja lu delete"
> coba code nya sini

eh maaf

**Comment by Tanaka9531** [comment]
> > > Coba Aja Dulu
> > 
> > 
> > file nya aja lu delete"
> > coba code nya sini
> 
> eh maaf

bandicam 2020-12-14 15-23-46-900
Tuh

**Comment by Tanaka9531** [comment]
> > > > Coba Aja Dulu
> > > 
> > > 
> > > file nya aja lu delete"
> > > coba code nya sini
> > 
> > 
> > eh maaf
> 
> bandicam 2020-12-14 15-23-46-900
> Tuh

**Comment by Tanaka9531** [comment]
> > > Coba Aja Dulu
> > 
> > 
> > file nya aja lu delete"
> > coba code nya sini
> 
> eh maaf

	case 'say':
        const says = args.join(' ')
		await aruga.sendText(from, `${says}`)
		break

**Comment by Tanaka9531** [comment]
Mau Tanya Kalau Mau Ubah Url ini https://i.waifu.pics/DCZkCKD.gif Ke sticker gif gimana yah?

**Pull request closed without merging**
