### PR TITLE
Adding brainly-scraper module

### PR DESCRIPTION
**Pull request by TheSploit**
Taruhny di lib :v

### CODE REVIEW

**Comment by thoriqazzikra** [comment]
njir gua baru aja pull

**Comment by bagusdwip** [comment]
Emang brainly work kah? Ga undefined?

**Comment by TheSploit** [comment]
> njir gua baru aja pull

wkwk aing first mhank :v

**Comment by TheSploit** [comment]
> Emang brainly work kah? Ga undefined?

work ko

**Pull request merged**
