### PR TITLE
ANTI LINK

### PR DESCRIPTION
**Pull request by thoriqazzikra**
auto kick buat member

### CODE REVIEW

**Comment by Fucksociety666** [comment]
> auto kick buat member

Screenshot pada 2020-12-09 13-19-33

lah kok gk ke kick gw posisi jadi member

**Comment by thoriqazzikra** [comment]
> > auto kick buat member
> 
> Screenshot pada 2020-12-09 13-19-33
> 
> lah kok gk ke kick gw posisi jadi member

kan owner bot

**Comment by thoriqazzikra** [comment]
> > auto kick buat member
> 
> Screenshot pada 2020-12-09 13-19-33
> 
> lah kok gk ke kick gw posisi jadi member

coba suruh yg laen send linknya
posisi bot harus admin

**Comment by Fucksociety666** [comment]
hmm cukup masuk akal, nnnti ku coba

**Comment by Suryapardana** [comment]
Gabisa ngab disaya

**Comment by thoriqazzikra** [comment]
> Gabisa ngab disaya

di gua bisa kok

**Comment by Fucksociety666** [comment]
[EROR] ReferenceError: adminNumber is not defined

		const isAdmin = adminNumber.includes(pengirim) syntax

**Comment by thoriqazzikra** [comment]
> [EROR] ReferenceError: adminNumber is not defined
> 
> ```
> 	const isAdmin = adminNumber.includes(pengirim) syntax
> ```
> 
> EROR] ReferenceError: isAdmin is not defined
> at HandleMsg (/home/fsociety/whatsapp-bot/HandleMsg.js:132:46)
> at runMicrotasks ()
> 
> if (isGroupMsg && !isGroupAdmins && !isAdmin && !isOwnerBot){

yang isAdmin didelete ajaa

**Comment by Fucksociety666** [comment]
done thanks

**Comment by Tanaka9531** [comment]
cara kasi enable dengan disable gimana bang

**Comment by NaldoMota1** [comment]
apakah Anda memerlukan hal lain untuk membuatnya berfungsi? Punyaku tidak berfungsi

**Comment by thoriqazzikra** [comment]
> cara kasi enable dengan disable gimana bang

lagi nyari, sebernya ada di git sebelah cmn ya kedetect syntax

**Comment by thoriqazzikra** [comment]
> apakah Anda memerlukan hal lain untuk membuatnya berfungsi? Punyaku tidak berfungsi

noo, that's will work for a member, not for a owner bot
you should try with your friend or something to see that's will work or not

**Comment by NaldoMota1** [comment]
ReferenceError: ownerNumber is not defined

**Comment by NaldoMota1** [comment]
I get this error

**Comment by thoriqazzikra** [comment]
> ReferenceError: ownerNumber is not defined

add this 
 

` const ownerNumber = "62895334950905@c.us"
  const isOwner = ownerNumber.includes(sender.id)`

**Comment by thoriqazzikra** [comment]
> > ReferenceError: ownerNumber is not defined
> 
> add this
> 
> ` const ownerNumber = "62895334950905@c.us"` 
`const isOwner = ownerNumber.includes(sender.id)`

**Pull request closed without merging**
