### PR TITLE
Cek 

### PR DESCRIPTION
**Pull request by Tanaka9531**
bandicam 2020-12-16 14-36-44-531

Gunanya Kayak Gitu

### CODE REVIEW

**Comment by MSI0072** [comment]
ngap kalau pesan biasa ke reply juga
image

**Comment by Tanaka9531** [comment]
> ngap kalau pesan biasa ke reply juga
> image

        case 'snk':
            kaguya.reply(from, snk, id)
            break
        default:
            if (body.startsWith('#')) {
                kaguya.reply(from, `Maaf ${pushname}, Command *${args[0]}* Tidak Terdaftar Di Dalam *#menu*!`, id)
            }
            console.log(color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
            }

**Comment by Tanaka9531** [comment]
> > ngap kalau pesan biasa ke reply juga
> > image
> 
> ```
>     case 'snk':
>         kaguya.reply(from, snk, id)
>         break
>     default:
>         if (body.startsWith('#')) {
>             kaguya.reply(from, `Maaf ${pushname}, Command *${args[0]}* Tidak Terdaftar Di Dalam *#menu*!`, id)
>         }
>         console.log(color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
>         }
> ```

bandicam 2020-12-16 22-53-27-201

Tuh Coba Udh Gak Lagi
bandicam 2020-12-16 22-54-05-113

**Comment by Tanaka9531** [comment]
Udah Ku Perbaiki tuh coba Lagi Btw yang tulisannya kaguya di ganti ya :)
bandicam 2020-12-16 22-53-27-201

**Comment by m1dark** [comment]
default:
            if (body.startsWith('#')) {
                kaguya.reply(from, `Baka ${pushname}, Fitur Yang Kamu Ketik Gak Ada Di Menu`, id)
            }
            (color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
            }

Taro di mana?

**Comment by Tanaka9531** [comment]
> ```
>     default:
>         if (body.startsWith('#')) {
>             kaguya.reply(from, `Baka ${pushname}, Fitur Yang Kamu Ketik Gak Ada Di Menu`, id)
>         }
>         (color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
>         }
> ```
> 
> Taro di mana?

bagian bawa kan udah ada ku tulis tuh tinggal ganti aja

**Comment by Tanaka9531** [comment]
> ```
>     default:
>         if (body.startsWith('#')) {
>             kaguya.reply(from, `Baka ${pushname}, Fitur Yang Kamu Ketik Gak Ada Di Menu`, id)
>         }
>         (color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
>         }
> ```
> 
> Taro di mana?

cek https://github.com/ArugaZ/whatsapp-bot/pull/220/commits/a12aa81141c6112e822f8825c43f979de36b445a disitu

**Comment by thoriqazzikra** [comment]
> > ```
> >     default:
> >         if (body.startsWith('#')) {
> >             kaguya.reply(from, `Baka ${pushname}, Fitur Yang Kamu Ketik Gak Ada Di Menu`, id)
> >         }
> >         (color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
> >         }
> > ```
> > 
> > 
> > Taro di mana?
> 
> cek [a12aa81](https://github.com/ArugaZ/whatsapp-bot/commit/a12aa81141c6112e822f8825c43f979de36b445a) disitu

Ngab, kok di gua ga bisa ya yang if body.. kek gini

```if (body == 'Bot'){
aruga.reply(from, 'Naonn euyy' , id)
}```

Kok ga ngerespon ya? Ada yg kurang kah?, Pdahal kmrn ngerespon, skrng udh ngga

**Comment by Tanaka9531** [comment]
> > > ```
> > >     default:
> > >         if (body.startsWith('#')) {
> > >             kaguya.reply(from, `Baka ${pushname}, Fitur Yang Kamu Ketik Gak Ada Di Menu`, id)
> > >         }
> > >         (color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
> > >         }
> > > ```
> > > 
> > > 
> > > Taro di mana?
> > 
> > 
> > cek [a12aa81](https://github.com/ArugaZ/whatsapp-bot/commit/a12aa81141c6112e822f8825c43f979de36b445a) disitu
> 
> Ngab, kok di gua ga bisa ya yang if body.. kek gini
> 
> if (body == 'Bot'){
> aruga.reply(from, 'Naonn euyy' , id)
> }
> 
> Kok ga ngerespon ya? Ada yg kurang kah?, Pdahal kmrn ngerespon, skrng udh ngga

oh... aku tau setelah aku test2 aku udh dpt apa salahnya

**Comment by Tanaka9531** [comment]
> > > > ```
> > > >     default:
> > > >         if (body.startsWith('#')) {
> > > >             kaguya.reply(from, `Baka ${pushname}, Fitur Yang Kamu Ketik Gak Ada Di Menu`, id)
> > > >         }
> > > >         (color('[UNLISTED]', 'red'), color('yellow'), 'Unregistered Command from', color(pushname))
> > > >         }
> > > > ```
> > > > 
> > > > 
> > > > Taro di mana?
> > > 
> > > 
> > > cek [a12aa81](https://github.com/ArugaZ/whatsapp-bot/commit/a12aa81141c6112e822f8825c43f979de36b445a) disitu
> > 
> > 
> > Ngab, kok di gua ga bisa ya yang if body.. kek gini
> > if (body == 'Bot'){
> > aruga.reply(from, 'Naonn euyy' , id)
> > }
> > Kok ga ngerespon ya? Ada yg kurang kah?, Pdahal kmrn ngerespon, skrng udh ngga
> 
> oh... aku tau setelah aku test2 aku udh dpt apa salahnya

nih wa aku wa.me/62816243737 kalau mau xiixixixixixix

**Comment by MSI0072** [comment]
`if (body.startsWith(prefix)) {
    return aruga.reply(from, `*Perintah tidak ditemukan, silahkan cek kembali di ${prefix}menu*`, id)
   .then(() => console.log(color('[Not Found]', 'red'), color(moment(t * 1000).format('DD/MM/YY HH:mm:ss'), 'yellow'), color(`${command} [${args.length}]`), 'from', color(pushname)))
} `


kalo gw gini ngab

**Comment by MSI0072** [comment]
> if (body.startsWith(prefix)) {
    return aruga.reply(from, `*Perintah tidak ditemukan, silahkan cek kembali di ${prefix}menu*`, id)
   .then(() => console.log(color('[Not Found]', 'red'), color(moment(t * 1000).format('DD/MM/YY HH:mm:ss'), 'yellow'), color(`${command} [${args.length}]`), 'from', color(pushname)))
} 

Kalo gw gini ngab

**Comment by MSI0072** [comment]
default:
        if (body.startsWith(prefix)) {
    return aruga.reply(from, `*Perintah tidak ditemukan, silahkan cek kembali di ${prefix}menu*`, id)
    .then(() => console.log(color('[Not Found]', 'red'), color(moment(t * 1000).format('DD/MM/YY HH:mm:ss'), 'yellow'),color(`${command} [${args.length}]`), 'from', color(pushname)))
    } 

di gw gini bisa ngab

**Pull request closed without merging**
